import { Head, Link, useForm } from '@inertiajs/react';
import { useRef, useState } from 'react';
import AppLayout from '../../Layouts/AppLayout';
import Icon from '../../Components/Icon';
import { dateTime } from '../../Utils/format';

export default function Imports({ batches }) {
    const form=useForm({file:null}); const input=useRef(); const [drag,setDrag]=useState(false);
    const upload=(file)=>{if(file) form.setData('file',file);};
    const submit=(e)=>{e.preventDefault(); if(!form.data.file) return; form.post('/imports/preview',{forceFormData:true});};
    return <AppLayout title="Import Data" subtitle="Masukkan database prospek hasil riset ChatGPT atau sumber lain tanpa copy-paste satu per satu." action={<Link href="/prospects" className="btn btn-secondary"><Icon name="building" size={17}/>Lihat Prospek</Link>}>
        <Head title="Import Data"/>
        <section className="import-hero-v2"><div><span className="eyebrow light">Santovate import engine</span><h2>Database dari saya → template → CRM.</h2><p>Gunakan template baku agar data yang Anda minta dari ChatGPT bisa langsung dipreview, divalidasi, lalu masuk ke database prospek.</p><div className="import-hero-actions"><a href="/imports/template" className="btn btn-white"><Icon name="download" size={17}/>Download Template</a><a href="/imports/sample" className="btn btn-outline-light"><Icon name="download" size={17}/>Contoh 30 Data</a></div></div><span className="import-visual"><Icon name="upload" size={38}/></span></section>
        <div className="import-layout"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Upload</span><h3>Import prospect database</h3></div><span className="step-chip">1 / 2</span></div><form onSubmit={submit}>
            <div className={`upload-zone ${drag?'drag':''} ${form.data.file?'has-file':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);upload(e.dataTransfer.files?.[0])}} onClick={()=>input.current?.click()}><input ref={input} type="file" accept=".xlsx,.xls,.csv" hidden onChange={e=>upload(e.target.files?.[0])}/><span className="upload-icon"><Icon name={form.data.file?'check':'upload'} size={25}/></span><strong>{form.data.file?form.data.file.name:'Tarik file ke sini atau klik untuk memilih'}</strong><p>XLSX, XLS, CSV · maksimal 5 MB · maksimal 1.000 baris</p></div>
            {form.errors.file&&<div className="alert alert-error">{form.errors.file}</div>}<button className="btn btn-primary btn-block btn-lg" disabled={!form.data.file||form.processing}>{form.processing?'Membaca file...':'Preview & Validasi Data'}<Icon name="chevron" size={17}/></button>
        </form></section>
        <aside className="panel import-guide"><div className="panel-head"><div><span className="eyebrow">Format data</span><h3>Alur yang aman</h3></div></div><ol className="number-list"><li><span>1</span><div><strong>Minta data ke ChatGPT</strong><p>Contoh: “Cari 50 freight forwarder Jakarta dan buat dalam template import Santovate CRM.”</p></div></li><li><span>2</span><div><strong>Upload file</strong><p>CRM memeriksa kolom, format, duplikat, dan baris yang error.</p></div></li><li><span>3</span><div><strong>Preview sebelum commit</strong><p>Data belum masuk database sampai Anda menekan tombol Import.</p></div></li></ol><div className="admin-note"><Icon name="alert" size={17}/><p>Import hanya tersedia untuk Admin agar database prospek tetap terkontrol dan tidak mudah dipenuhi data ganda.</p></div></aside></div>
        <section className="panel no-pad import-history"><div className="panel-head padded"><div><span className="eyebrow">Audit</span><h3>Riwayat import</h3></div></div><div className="clean-table-wrap"><table className="clean-table"><thead><tr><th>File</th><th>Admin</th><th>Total</th><th>Baru</th><th>Update</th><th>Skip</th><th>Error</th><th>Distribusi</th><th>Waktu</th><th></th></tr></thead><tbody>{batches.data.map(b=><tr key={b.id}><td><strong>{b.filename}</strong></td><td>{b.importer?.name||'—'}</td><td>{b.total_rows}</td><td><span className="text-success">{b.imported_rows}</span></td><td>{b.updated_rows}</td><td>{b.skipped_rows}</td><td><span className={b.error_rows?'text-danger':''}>{b.error_rows}</span></td><td><div className="stacked-cell"><strong>{b.assignment_summary?.assigned_total||0} assigned</strong><small>{b.assignment_summary?.sales?.length||0} AE · {b.assignment_summary?.unassigned||0} belum ditugaskan</small></div></td><td>{dateTime(b.created_at)}</td><td><Link href={`/imports/${b.id}`} className="icon-button"><Icon name="chevron" size={16}/></Link></td></tr>)}</tbody></table>{!batches.data.length&&<div className="mini-empty padded">Belum ada riwayat import.</div>}</div></section>
    </AppLayout>;
}
