import { Head, Link, router, useForm, usePage } from '@inertiajs/react';
import AppLayout from '../../Layouts/AppLayout';
import Icon from '../../Components/Icon';
import { Avatar, PriorityBadge, ScoreDots, StatusBadge } from '../../Components/Ui';
import { dateTime, isDue, money } from '../../Utils/format';

export default function Show({ prospect:p, statuses, qualificationStatuses, activityTypes }) {
    const { auth }=usePage().props;
    const activity=useForm({type:'note',title:'',description:'',contact_person:'',client_feedback:'',objection:'',next_action:'',occurred_at:'',next_follow_up_at:'',status:''});
    const submitActivity=(e)=>{e.preventDefault();activity.post(`/prospects/${p.id}/activities`,{preserveScroll:true,onSuccess:()=>activity.reset('title','description','contact_person','client_feedback','objection','next_action','occurred_at')});};
    const changeStatus=(status)=>router.patch(`/prospects/${p.id}/status`,{status},{preserveScroll:true});
    const remove=()=>{if(confirm(`Hapus ${p.company_name}?`))router.delete(`/prospects/${p.id}`)};
    const digits=(p.phone||'').replace(/\D/g,'');
    return <AppLayout title={p.company_name} subtitle={[p.city,p.service,p.route].filter(Boolean).join(' · ')||'Profil prospek'} action={<div className="action-group"><Link href="/prospects" className="btn btn-secondary"><Icon name="arrowLeft" size={17}/>Kembali</Link><Link href={`/opportunities/create?prospect_id=${p.id}`} className="btn btn-soft">+ Opportunity</Link><Link href={`/quotations/create?prospect_id=${p.id}`} className="btn btn-soft">+ Quotation</Link><Link href={`/prospects/${p.id}/edit`} className="btn btn-primary"><Icon name="edit" size={17}/>Edit</Link></div>}>
        <Head title={p.company_name}/>
        <section className="prospect-hero panel"><div className="prospect-hero-main"><span className="hero-company-avatar">{p.company_name?.[0]}</span><div><div className="hero-badges"><PriorityBadge priority={p.priority}/><StatusBadge status={p.status} label={p.status_label}/><span className="badge badge-neutral">{qualificationStatuses?.[p.qualification_status]||p.qualification_status}</span></div><h2>{p.company_name}</h2><p>{p.pain_hypothesis||'Belum ada dugaan masalah. Lakukan riset atau discovery.'}</p></div></div><div className="hero-score"><strong>{p.total_score}<small>/9</small></strong><ScoreDots value={p.total_score>=7?3:p.total_score>=4?2:1}/><span>Lead score</span></div></section>
        <section className="metric-grid commercial-metrics"><div className="panel"><span>Estimated Deal</span><strong>{money(p.estimated_deal_value)}</strong></div><div className="panel"><span>Budget</span><strong>{p.estimated_budget?money(p.estimated_budget):'—'}</strong></div><div className="panel"><span>Probability</span><strong>{p.probability||0}%</strong></div><div className="panel"><span>Actual Deal</span><strong>{p.actual_deal_value?money(p.actual_deal_value):'—'}</strong></div></section>
        <div className="detail-layout"><div className="detail-main">
            <section className="panel"><div className="panel-head"><div><span className="eyebrow">Qualification</span><h3>Account & decision context</h3></div></div><div className="detail-info-grid"><div><span>PIC</span><strong>{p.contact_name||'—'} {p.contact_position?`· ${p.contact_position}`:''}</strong></div><div><span>Decision Maker</span><strong>{p.decision_maker_name||'—'} {p.decision_maker_position?`· ${p.decision_maker_position}`:''}</strong></div><div><span>Sistem Saat Ini</span><strong>{p.current_system||'—'}</strong></div><div><span>Timeline</span><strong>{p.expected_timeline||'—'}</strong></div><div><span>Target Go-Live</span><strong>{p.target_go_live||'—'}</strong></div><div><span>Urgency</span><strong>{p.urgency||'—'}</strong></div><div><span>Next Action</span><strong>{p.next_action||'—'}</strong></div><div><span>AE</span><strong>{p.assigned_user?.name||'Belum diassign'}</strong></div></div></section>
            <section className="panel"><div className="panel-head"><div><span className="eyebrow">Opportunities</span><h3>Peluang komersial</h3></div><Link href={`/opportunities/create?prospect_id=${p.id}`} className="btn btn-soft">+ Opportunity</Link></div>{p.opportunities?.length?<div className="commercial-list">{p.opportunities.map(o=><Link key={o.id} href={`/opportunities/${o.id}`}><div><strong>{o.name}</strong><small>{o.stage_label} · {o.probability}% · {o.owner?.name||'Unassigned'}</small></div><b>{money(o.expected_value)}</b></Link>)}</div>:<div className="mini-empty">Belum ada opportunity.</div>}</section>
            <section className="panel"><div className="panel-head"><div><span className="eyebrow">Quotations & Deals</span><h3>Commercial history</h3></div></div><div className="commercial-split"><div><h4>Quotations</h4>{p.quotations?.length?<div className="commercial-list">{p.quotations.map(q=><Link key={q.id} href={`/quotations/${q.id}`}><div><strong>{q.quotation_number}</strong><small>{q.status_label} · Rev.{q.revision_number}</small></div><b>{money(q.grand_total)}</b></Link>)}</div>:<div className="mini-empty">Belum ada quotation.</div>}</div><div><h4>Deals</h4>{p.deals?.length?<div className="commercial-list">{p.deals.map(d=><Link key={d.id} href={`/deals/${d.id}`}><div><strong>{d.deal_number}</strong><small>{d.closing_date}</small></div><b>{money(d.actual_deal_value)}</b></Link>)}</div>:<div className="mini-empty">Belum ada deal.</div>}</div></div></section>
            <section className="panel"><div className="panel-head"><div><span className="eyebrow">Activity timeline</span><h3>Riwayat interaksi</h3></div><span className="count-bubble">{p.activities?.length||0}</span></div><form className="activity-form" onSubmit={submitActivity}><div className="activity-row"><select value={activity.data.type} onChange={e=>activity.setData('type',e.target.value)}>{Object.entries(activityTypes).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input value={activity.data.title} onChange={e=>activity.setData('title',e.target.value)} placeholder="Judul aktivitas *"/><select value={activity.data.status} onChange={e=>activity.setData('status',e.target.value)}><option value="">Pipeline tetap</option>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><div className="activity-row"><input value={activity.data.contact_person} onChange={e=>activity.setData('contact_person',e.target.value)} placeholder="Contact person"/><input value={activity.data.next_action} onChange={e=>activity.setData('next_action',e.target.value)} placeholder="Next action"/></div><textarea rows="3" value={activity.data.description} onChange={e=>activity.setData('description',e.target.value)} placeholder="Summary aktivitas..."/><div className="activity-row"><textarea rows="2" value={activity.data.client_feedback} onChange={e=>activity.setData('client_feedback',e.target.value)} placeholder="Client feedback"/><textarea rows="2" value={activity.data.objection} onChange={e=>activity.setData('objection',e.target.value)} placeholder="Objection / concern"/></div><div className="activity-row"><label><span>Follow-up berikutnya</span><input type="datetime-local" value={activity.data.next_follow_up_at} onChange={e=>activity.setData('next_follow_up_at',e.target.value)}/></label><button className="btn btn-dark" disabled={activity.processing}><Icon name="plus" size={16}/>Catat Aktivitas</button></div>{Object.values(activity.errors).length>0&&<small className="field-error">{Object.values(activity.errors)[0]}</small>}</form><div className="timeline">{p.activities?.length?p.activities.map(a=><article className="timeline-item" key={a.id}><span className={`timeline-icon activity-${a.type}`}><Icon name={a.type==='meeting'?'users':a.type==='email'?'mail':a.type==='call'?'phone':a.type==='customer_reply'?'whatsapp':'briefcase'} size={16}/></span><div><div className="timeline-top"><strong>{a.title}</strong><time>{dateTime(a.occurred_at)}</time></div>{a.description&&<p>{a.description}</p>}{(a.client_feedback||a.objection||a.next_action)&&<div className="activity-insights">{a.client_feedback&&<span><b>Feedback:</b> {a.client_feedback}</span>}{a.objection&&<span><b>Objection:</b> {a.objection}</span>}{a.next_action&&<span><b>Next:</b> {a.next_action}</span>}</div>}<small>{a.type_label} · {a.contact_person||a.user?.name||'System'}</small></div></article>):<div className="mini-empty">Belum ada aktivitas.</div>}</div></section>
            {p.assignment_histories?.length>0&&<section className="panel"><div className="panel-head"><div><span className="eyebrow">Ownership</span><h3>Assignment history</h3></div></div><div className="commercial-list">{p.assignment_histories.map(h=><div key={h.id}><div><strong>{h.from_user?.name||'Unassigned'} → {h.to_user?.name||'Unassigned'}</strong><small>{h.reason||'Reassignment'} · {h.changed_by?.name||'System'} · {dateTime(h.created_at)}</small></div></div>)}</div></section>}
        </div><aside className="detail-side"><section className="panel sticky-panel"><span className="eyebrow">Next action</span><h3 className="side-title">{p.next_action||'Hubungi & lanjutkan'}</h3><div className="contact-card"><Avatar name={p.contact_name||p.company_name}/><div><strong>{p.contact_name||'PIC belum ditemukan'}</strong><span>{p.contact_position||'Cari decision maker yang tepat'}</span></div></div><div className="quick-actions">{p.phone&&<a href={`tel:${p.phone}`} className="quick-action"><Icon name="phone" size={18}/><span>Telepon</span></a>}{digits&&<a href={`https://wa.me/${digits}`} target="_blank" rel="noreferrer" className="quick-action"><Icon name="whatsapp" size={18}/><span>WhatsApp</span></a>}{p.email&&<a href={`mailto:${p.email}`} className="quick-action"><Icon name="mail" size={18}/><span>Email</span></a>}</div><div className={`followup-box ${isDue(p.next_follow_up_at)?'overdue':''}`}><Icon name="calendar" size={19}/><div><span>Follow-up berikutnya</span><strong>{p.next_follow_up_at?dateTime(p.next_follow_up_at):'Belum dijadwalkan'}</strong></div></div><label className="field compact-field"><span>Update pipeline</span><select value={p.status} onChange={e=>changeStatus(e.target.value)}>{Object.entries(statuses).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><div className="source-box"><span>Sumber data</span><strong>{p.source_name||'Manual'}</strong>{p.source_url&&<a href={p.source_url} target="_blank" rel="noreferrer">Buka sumber <Icon name="external" size={14}/></a>}</div>{p.notes&&<div className="notes-box"><span>Catatan internal</span><p>{p.notes}</p></div>}{auth.user.is_admin&&<button className="btn btn-danger-soft btn-block" onClick={remove}><Icon name="trash" size={16}/>Hapus Prospek</button>}</section></aside></div>
    </AppLayout>;
}
