import { Head, Link, router } from '@inertiajs/react';
import AppLayout from '../../Layouts/AppLayout';
import { Badge, MetricCard, EmptyState } from '../../Components/Ui';
import { compactMoney, money } from '../../Utils/format';

const labels={estimated:'Estimated',pending_payment:'Pending Payment',partially_earned:'Partially Earned',earned:'Earned',approved:'Approved',paid:'Paid'};
const tones={estimated:'neutral',pending_payment:'info',partially_earned:'warning',earned:'success',approved:'violet',paid:'success'};
export default function Commissions({commissions,summary,canManage}){
    const approve=(c)=>router.post(`/finance/commissions/${c.id}/approve`);
    const pay=(c)=>{const reference=window.prompt('Reference payout (opsional):')||'';router.post(`/finance/commissions/${c.id}/pay`,{reference_number:reference,paid_at:new Date().toISOString().slice(0,10)});};
    return <AppLayout title="Commission Ledger" subtitle="Audit trail komisi: potential → earned → approved → paid." action={<div className="action-group"><Link href="/sales-guide" className="btn btn-soft">Panduan</Link><Link href="/finance" className="btn btn-secondary">Finance</Link></div>}>
        <Head title="Commission Ledger"/>
        <section className="sv-context-banner"><div><strong>Commission Ledger bukan payment ledger.</strong><p>Potential adalah potensi maksimum; Earned terbentuk dari pembayaran client terverifikasi; Approved siap payout; Paid sudah dibayarkan ke Sales.</p></div></section>
        <section className="metric-grid finance-commission-metrics"><MetricCard label="Potential" value={`Rp${compactMoney(summary.potential_commission)}`} helper="maximum commission" icon="target" accent="violet"/><MetricCard label="Earned" value={`Rp${compactMoney(summary.earned_commission)}`} helper="verified collection" icon="check" accent="green"/><MetricCard label="Approved" value={`Rp${compactMoney(summary.approved_commission)}`} helper="ready for payout" icon="briefcase" accent="blue"/><MetricCard label="Paid" value={`Rp${compactMoney(summary.commission_paid)}`} helper="recorded payout" icon="check" accent="green"/></section>
        <section className="panel no-pad sv-data-panel">{commissions.data.length?<>
            <div className="clean-table-wrap desktop-only"><table className="clean-table sv-data-table"><thead><tr><th>Deal / Client</th><th>Sales</th><th>Commissionable</th><th>Potential</th><th>Earned</th><th>Approved</th><th>Paid</th><th>Status</th><th>Action</th></tr></thead><tbody>{commissions.data.map(c=><tr key={c.id}><td><strong>{c.deal.deal_number}</strong><small className="cell-sub">{c.deal.client}</small>{c.adjustment_due>0&&<small className="cell-sub text-danger">Adjustment {money(c.adjustment_due)}</small>}</td><td>{c.sales?.name||'—'}</td><td>{money(c.commissionable_value)}</td><td>{money(c.potential_amount)}</td><td><strong>{money(c.earned_amount)}</strong></td><td>{money(c.approved_amount)}</td><td>{money(c.paid_amount)}</td><td><Badge tone={tones[c.status]||'neutral'}>{labels[c.status]||c.status}</Badge></td><td>{canManage?<div className="action-group">{c.earned_amount>c.approved_amount+0.01&&<button className="btn btn-sm btn-soft" onClick={()=>approve(c)}>Approve</button>}{c.payable_amount>0.01&&<button className="btn btn-sm btn-primary" onClick={()=>pay(c)}>Mark Paid</button>}</div>:'—'}</td></tr>)}</tbody></table></div>
            <div className="sv-mobile-data-list mobile-only">{commissions.data.map(c=><article className="sv-mobile-data-card" key={c.id}><div className="sv-mobile-card-head"><div><small>{c.deal.deal_number}</small><strong>{c.deal.client}</strong></div><Badge tone={tones[c.status]||'neutral'}>{labels[c.status]||c.status}</Badge></div><div className="sv-mobile-card-metrics"><span><small>Earned</small><strong>{money(c.earned_amount)}</strong></span><span><small>Paid</small><strong>{money(c.paid_amount)}</strong></span></div><div className="sv-mobile-card-row"><span>Sales</span><strong>{c.sales?.name||'—'}</strong></div>{canManage&&<div className="action-group">{c.earned_amount>c.approved_amount+0.01&&<button className="btn btn-sm btn-soft" onClick={()=>approve(c)}>Approve</button>}{c.payable_amount>0.01&&<button className="btn btn-sm btn-primary" onClick={()=>pay(c)}>Mark Paid</button>}</div>}</article>)}</div>
        </>:<EmptyState icon="target" title="Belum ada commission ledger" description="Ledger akan terbentuk dari Deal Won dan pembayaran client."/>}</section>
    </AppLayout>;
}
