import { Head, Link, router } from '@inertiajs/react';
import AppLayout from '../../Layouts/AppLayout';
import Icon from '../../Components/Icon';
import { MetricCard, Badge, EmptyState } from '../../Components/Ui';
import { compactMoney, date, money } from '../../Utils/format';

const statusLabel={draft:'Draft',issued:'Issued',partially_paid:'Partially Paid',paid:'Paid',overdue:'Overdue',void:'Void'};
const statusTone={draft:'neutral',issued:'info',partially_paid:'warning',paid:'success',overdue:'danger',void:'neutral'};

export default function FinanceIndex({ invoices, summary, filters, canManage }) {
    const change=(key,value)=>router.get('/finance',{...filters,[key]:value||undefined},{preserveState:true,replace:true});
    return <AppLayout title="Finance" subtitle="Invoice, collection, outstanding, refund, dan komisi dari data pembayaran terverifikasi." action={<div className="action-group"><Link href="/sales-guide#finance" className="btn btn-soft">Panduan Finance</Link><Link href="/finance/commissions" className="btn btn-soft">Commission Ledger</Link>{canManage&&<Link href="/finance/invoices/create" className="btn btn-primary"><Icon name="plus" size={17}/>Invoice</Link>}</div>}>
        <Head title="Finance"/>
        <section className="sv-finance-guide-strip"><article><span>Outstanding</span><strong>Sisa invoice yang belum dibayar.</strong></article><article><span>Net Collected</span><strong>Verified payment setelah refund.</strong></article><article><span>Earned Commission</span><strong>Komisi dari collection yang terverifikasi.</strong></article><Link href="/sales-guide">Semua istilah <Icon name="chevron" size={14}/></Link></section>
        <section className="metric-grid finance-metric-grid"><MetricCard label="Actual Deal" value={`Rp${compactMoney(summary.actual_deal)}`} helper="won value" icon="check" accent="green"/><MetricCard label="Invoiced" value={`Rp${compactMoney(summary.invoiced)}`} helper="invoice aktif" icon="briefcase" accent="blue"/><MetricCard label="Net Collected" value={`Rp${compactMoney(summary.paid_by_client)}`} helper="verified after refund" icon="check" accent="green"/><MetricCard label="Outstanding" value={`Rp${compactMoney(summary.outstanding)}`} helper={`${summary.overdue_count||0} overdue`} icon="alert" accent="red"/><MetricCard label="Potential Commission" value={`Rp${compactMoney(summary.potential_commission)}`} helper="maximum potential" icon="target" accent="violet"/><MetricCard label="Earned Commission" value={`Rp${compactMoney(summary.earned_commission)}`} helper="based on collection" icon="target" accent="amber"/><MetricCard label="Commission Paid" value={`Rp${compactMoney(summary.commission_paid)}`} helper="recorded payout" icon="check" accent="green"/></section>
        <section className="panel commercial-toolbar finance-toolbar sv-toolbar-modern"><div className="search-box"><Icon name="search" size={17}/><input value={filters.q||''} onChange={e=>change('q',e.target.value)} placeholder="Cari invoice / deal / client..."/></div><select value={filters.status||''} onChange={e=>change('status',e.target.value)}><option value="">Semua status</option>{Object.entries(statusLabel).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></section>
        <section className="panel no-pad sv-data-panel">{invoices.data.length?<>
            <div className="clean-table-wrap desktop-only"><table className="clean-table finance-table sv-data-table"><thead><tr><th>Invoice</th><th>Client / Deal</th><th>AE</th><th>Issued / Due</th><th>Total</th><th>Net Paid</th><th>Outstanding</th><th>Status</th><th/></tr></thead><tbody>{invoices.data.map(invoice=><tr key={invoice.id}><td><Link href={`/finance/invoices/${invoice.id}`} className="sv-primary-cell"><strong>{invoice.invoice_number}</strong>{invoice.schedule&&<small>{invoice.schedule}</small>}</Link></td><td><strong>{invoice.deal.client||'—'}</strong><small className="cell-sub">{invoice.deal.deal_number}</small></td><td>{invoice.deal.owner||'—'}</td><td><span>{date(invoice.issue_date)}</span><small className="cell-sub">Due {date(invoice.due_date)}</small></td><td><strong>{money(invoice.total_amount)}</strong></td><td>{money(Math.max(0,invoice.paid_amount-invoice.refunded_amount))}</td><td><strong className={invoice.outstanding_amount>0?'text-danger':'text-success'}>{money(invoice.outstanding_amount)}</strong></td><td><Badge tone={statusTone[invoice.status]||'neutral'}>{statusLabel[invoice.status]||invoice.status}</Badge></td><td><Link className="icon-button" href={`/finance/invoices/${invoice.id}`}><Icon name="chevron" size={17}/></Link></td></tr>)}</tbody></table></div>
            <div className="sv-mobile-data-list mobile-only">{invoices.data.map(invoice=><Link href={`/finance/invoices/${invoice.id}`} className="sv-mobile-data-card" key={invoice.id}><div className="sv-mobile-card-head"><div><small>{invoice.invoice_number}</small><strong>{invoice.deal.client||'Client'}</strong></div><Badge tone={statusTone[invoice.status]||'neutral'}>{statusLabel[invoice.status]||invoice.status}</Badge></div><div className="sv-mobile-card-metrics"><span><small>Total</small><strong>{money(invoice.total_amount)}</strong></span><span><small>Outstanding</small><strong className={invoice.outstanding_amount>0?'text-danger':'text-success'}>{money(invoice.outstanding_amount)}</strong></span></div><div className="sv-mobile-card-row"><span>Net Paid</span><strong>{money(Math.max(0,invoice.paid_amount-invoice.refunded_amount))}</strong></div><div className="sv-mobile-card-row"><span>Due</span><strong>{date(invoice.due_date)}</strong></div></Link>)}</div>
            {invoices.links?.length>3&&<div className="table-footer"><span>Page {invoices.current_page} of {invoices.last_page}</span><div className="pagination">{invoices.links.map((link,index)=>link.url?<Link key={index} href={link.url} className={link.active?'active':''} dangerouslySetInnerHTML={{__html:link.label}}/>:<span key={index} dangerouslySetInnerHTML={{__html:link.label}}/>)}</div></div>}
        </>:<EmptyState icon="briefcase" title="Belum ada invoice" description="Invoice dibuat dari Deal Won oleh Finance atau Administrator."/>}</section>
    </AppLayout>;
}
