import { Head } from '@inertiajs/react';
import { date, money } from '../../Utils/format';

export default function InvoicePrint({ invoice:i }) {
    const organization = i.organization || {};
    const brand = organization.invoice_brand_name || organization.name || 'Organization';
    const orgContact = [organization.contact_email, organization.contact_phone].filter(Boolean).join(' · ');

    return <div className="finance-print-page">
        <Head title={i.invoice_number}/>
        <div className="finance-print-actions"><button onClick={()=>window.print()}>Print / Save PDF</button></div>
        <header>
            <div>
                <strong className="finance-print-brand">{brand}</strong>
                <span>Commercial Invoice</span>
                {organization.address&&<small>{organization.address}</small>}
                {orgContact&&<small>{orgContact}</small>}
            </div>
            <div><h1>{i.invoice_number}</h1><p>Status: {i.status}</p></div>
        </header>
        <section className="finance-print-client">
            <div><span>Bill To</span><h2>{i.deal.client}</h2><p>{i.deal.contact_name || ''}<br/>{i.deal.email || ''}<br/>{i.deal.phone || ''}</p></div>
            <div><span>Deal</span><strong>{i.deal.deal_number}</strong><p>Account Executive: {i.deal.owner || '—'}</p></div>
            <div><span>Issue Date</span><strong>{date(i.issue_date)}</strong><span>Due Date</span><strong>{date(i.due_date)}</strong></div>
        </section>
        <table><thead><tr><th>Description</th><th>Amount</th></tr></thead><tbody><tr><td><strong>{i.schedule?.label || 'Commercial Services'}</strong><small>{i.notes || `${brand} commercial invoice`}</small></td><td>{money(i.subtotal)}</td></tr>{i.tax_amount>0&&<tr><td>Tax</td><td>{money(i.tax_amount)}</td></tr>}</tbody></table>
        <div className="finance-print-summary"><div><span>Subtotal</span><strong>{money(i.subtotal)}</strong></div><div><span>Tax</span><strong>{money(i.tax_amount)}</strong></div><div className="grand"><span>Total</span><strong>{money(i.total_amount)}</strong></div><div><span>Paid</span><strong>{money(i.net_paid_amount)}</strong></div><div><span>Outstanding</span><strong>{money(i.outstanding_amount)}</strong></div></div>
        {i.terms&&<section className="finance-print-terms"><span>Terms</span><p>{i.terms}</p></section>}
        <footer>{organization.invoice_footer || `${brand} · Generated by Santovate CRM`} · {i.invoice_number}</footer>
    </div>;
}
