import { Head, Link, router } from '@inertiajs/react';
import AppLayout from '../../Layouts/AppLayout';
import Icon from '../../Components/Icon';
import { money, dateTime } from '../../Utils/format';
export default function Show({opportunity:o}){const remove=()=>confirm('Hapus opportunity ini?')&&router.delete(`/opportunities/${o.id}`);return <AppLayout title={o.name} subtitle={o.prospect?.company_name||'Opportunity'} action={<div className="action-group"><Link href="/opportunities" className="btn btn-secondary"><Icon name="arrowLeft" size={17}/>Kembali</Link><Link href={`/quotations/create?opportunity_id=${o.id}`} className="btn btn-soft">Buat Quotation</Link><Link href={`/opportunities/${o.id}/edit`} className="btn btn-primary"><Icon name="edit" size={17}/>Edit</Link></div>}><Head title={o.name}/>
 <section className="commercial-hero panel"><div><span className="badge badge-info">{o.stage_label}</span><h2>{o.name}</h2><p>{o.business_problem||'Business problem belum dilengkapi.'}</p></div><div><small>Expected Value</small><strong>{money(o.expected_value)}</strong><span>{o.probability}% probability</span></div></section>
 <div className="detail-layout"><div className="detail-main"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Discovery</span><h3>Requirement & decision</h3></div></div><div className="commercial-detail-grid"><div><span>Current Process</span><p>{o.current_process||'—'}</p></div><div><span>Required Solution</span><p>{o.required_solution||'—'}</p></div><div><span>Required Features</span><p>{o.required_features||'—'}</p></div><div><span>Decision Maker</span><p>{o.decision_maker||'—'}</p></div><div><span>Decision Process</span><p>{o.decision_process||'—'}</p></div><div><span>Target Go-Live</span><p>{o.target_go_live||'—'}</p></div></div></section>
 <section className="panel"><div className="panel-head"><div><span className="eyebrow">Commercial</span><h3>Quotation</h3></div><Link href={`/quotations/create?opportunity_id=${o.id}`} className="btn btn-soft">+ Quotation</Link></div>{o.quotations?.length?<div className="commercial-list">{o.quotations.map(q=><Link key={q.id} href={`/quotations/${q.id}`}><div><strong>{q.quotation_number} · Rev.{q.revision_number}</strong><small>{q.status_label}</small></div><b>{money(q.grand_total)}</b></Link>)}</div>:<div className="mini-empty">Belum ada quotation.</div>}</section>
 {o.deals?.length>0&&<section className="panel"><div className="panel-head"><div><span className="eyebrow">Won</span><h3>Deal</h3></div></div><div className="commercial-list">{o.deals.map(d=><Link href={`/deals/${d.id}`} key={d.id}><div><strong>{d.deal_number}</strong><small>{d.closing_date}</small></div><b>{money(d.actual_deal_value)}</b></Link>)}</div></section>}</div>
 <aside className="detail-side"><section className="panel sticky-panel"><span className="eyebrow">Next Action</span><h3 className="side-title">{o.next_action||'Belum ditentukan'}</h3><div className="followup-box"><Icon name="calendar" size={19}/><div><span>Follow-up</span><strong>{o.next_follow_up_at?dateTime(o.next_follow_up_at):'Belum dijadwalkan'}</strong></div></div><div className="detail-info-grid single"><div><span>Owner</span><strong>{o.owner?.name||'—'}</strong></div><div><span>Budget</span><strong>{o.budget?money(o.budget):'—'}</strong></div><div><span>Urgency</span><strong>{o.urgency||'—'}</strong></div></div>{o.status==='lost'&&<div className="notes-box"><span>Lost</span><p>{o.lost_reason||'Tanpa alasan'}{o.competitor?` · Competitor: ${o.competitor}`:''}</p></div>}<button className="btn btn-danger-soft btn-block" onClick={remove}>Hapus Opportunity</button></section></aside></div>
 </AppLayout>}
