<?php
use App\Http\Controllers\ActivityController;
use App\Http\Controllers\ApprovalRequestController;
use App\Http\Controllers\Platform\DashboardController as PlatformDashboardController;
use App\Http\Controllers\Platform\ClientController as PlatformClientController;
use App\Http\Controllers\Platform\BusinessConfigurationController as PlatformBusinessConfigurationController;
use App\Http\Controllers\Platform\ApprovalController as PlatformApprovalController;
use App\Http\Controllers\Admin\BusinessSettingsController;
use App\Http\Controllers\Admin\ClientOnboardingController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\WhatsAppSettingsController;
use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\CampaignController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FollowUpController;
use App\Http\Controllers\FollowUpTemplateController;
use App\Http\Controllers\ImportController;
use App\Http\Controllers\NotificationController;
use App\Http\Controllers\DealController;
use App\Http\Controllers\CommercialPaymentResultController;
use App\Http\Controllers\Finance\CommissionController as FinanceCommissionController;
use App\Http\Controllers\Finance\FinanceController;
use App\Http\Controllers\Finance\InvoiceController as FinanceInvoiceController;
use App\Http\Controllers\Finance\PaymentController as FinancePaymentController;
use App\Http\Controllers\QuotationController;
use App\Http\Controllers\OpportunityController;
use App\Http\Controllers\PipelineController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\ProspectController;
use App\Http\Controllers\PublicController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\SalesTargetController;
use App\Http\Controllers\SalesGuideController;
use App\Http\Controllers\SubscriptionController;
use App\Http\Controllers\WhatsAppSendController;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;
Route::get('/',[PublicController::class,'home'])->name('home');
Route::get('/pricing',[PublicController::class,'plans'])->name('pricing.index');
Route::get('/plans',[PublicController::class,'plans'])->name('plans.index');
Route::get('/business-configurations',[PublicController::class,'configurations'])->name('business-configurations.index');
Route::get('/terms',fn()=>app(PublicController::class)->legal('terms'))->name('terms');
Route::get('/refund-policy',fn()=>app(PublicController::class)->legal('refund-policy'))->name('refund-policy');
Route::get('/privacy-policy',fn()=>app(PublicController::class)->legal('privacy-policy'))->name('privacy-policy');
Route::get('/faq',fn()=>app(PublicController::class)->legal('faq'))->name('faq.public');
Route::get('/contact',fn()=>app(PublicController::class)->legal('contact'))->name('contact');
Route::get('/payment-result/{reference}',CommercialPaymentResultController::class)->name('commercial-payment.result');
Route::middleware('guest')->group(function(){Route::get('/login',[AuthenticatedSessionController::class,'create'])->name('login');Route::post('/login',[AuthenticatedSessionController::class,'store'])->name('login.store');Route::get('/register',[RegistrationController::class,'create'])->name('register');Route::post('/register',[RegistrationController::class,'store'])->name('register.store');});
Route::middleware('auth')->group(function(){
    Route::post('/logout',[AuthenticatedSessionController::class,'destroy'])->name('logout');
    Route::middleware('platform.admin')->prefix('platform')->name('platform.')->group(function(){
        Route::get('/',PlatformDashboardController::class)->name('dashboard');
        Route::get('/clients',[PlatformClientController::class,'index'])->name('clients.index');
        Route::get('/configurations',[PlatformBusinessConfigurationController::class,'index'])->name('configurations.index');
        Route::put('/configurations/{configuration}',[PlatformBusinessConfigurationController::class,'update'])->name('configurations.update');
        Route::get('/approvals',[PlatformApprovalController::class,'index'])->name('approvals.index');
        Route::post('/approvals/{approval}/decision',[PlatformApprovalController::class,'decide'])->name('approvals.decide');
    });
    Route::get('/subscription/checkout',[SubscriptionController::class,'checkout'])->name('subscription.checkout');
    Route::patch('/subscription/checkout',[SubscriptionController::class,'updateSelection'])->name('subscription.selection');
    Route::post('/subscription/pay',[SubscriptionController::class,'pay'])->name('subscription.pay');
    Route::get('/subscription/payment-result',[SubscriptionController::class,'result'])->name('subscription.payment-result');
    Route::get('/subscription/status',[SubscriptionController::class,'status'])->name('subscription.status');
    Route::get('/subscription/payment-stream',[SubscriptionController::class,'stream'])->name('subscription.payment-stream');
    Route::middleware('subscription.active')->group(function(){
        Route::get('/profile',[ProfileController::class,'edit'])->name('profile.edit');Route::patch('/profile',[ProfileController::class,'update'])->name('profile.update');
        Route::get('/dashboard',DashboardController::class)->name('dashboard');
        Route::get('/approvals',[ApprovalRequestController::class,'index'])->name('approvals.index');
        Route::post('/approvals',[ApprovalRequestController::class,'store'])->name('approvals.store');
        Route::post('/approvals/{approval}/decision',[ApprovalRequestController::class,'decide'])->name('approvals.decide');
        Route::get('/sales-guide',[SalesGuideController::class,'index'])->name('sales-guide.index');
        Route::get('/prospects/check-duplicates',[ProspectController::class,'checkDuplicates'])->name('prospects.duplicates');
        Route::patch('/prospects/{prospect}/status',[ProspectController::class,'updateStatus'])->name('prospects.status');Route::resource('prospects',ProspectController::class);Route::post('/prospects/{prospect}/activities',[ActivityController::class,'store'])->name('prospects.activities.store');
        Route::resource('opportunities',OpportunityController::class);
        Route::post('/quotations/{quotation}/approve',[QuotationController::class,'approve'])->name('quotations.approve');
        Route::post('/quotations/{quotation}/send',[QuotationController::class,'send'])->name('quotations.send');
        Route::post('/quotations/{quotation}/accept',[QuotationController::class,'accept'])->name('quotations.accept');
        Route::post('/quotations/{quotation}/reject',[QuotationController::class,'reject'])->name('quotations.reject');
        Route::get('/quotations/{quotation}/print',[QuotationController::class,'print'])->name('quotations.print');
        Route::resource('quotations',QuotationController::class)->except(['destroy']);
        Route::get('/deals/from-quotation/{quotation}',[DealController::class,'createFromQuotation'])->name('deals.from-quotation.create');
        Route::post('/deals/from-quotation/{quotation}',[DealController::class,'storeFromQuotation'])->name('deals.from-quotation.store');
        Route::get('/deals',[DealController::class,'index'])->name('deals.index');
        Route::get('/deals/{deal}',[DealController::class,'show'])->name('deals.show');
        Route::post('/deals/{deal}/documents',[DealController::class,'uploadDocument'])->name('deals.documents.store');

        // Batch 3 - Finance, Payment, AR, Refund and Commission.
        Route::get('/finance',[FinanceController::class,'index'])->name('finance.index');
        Route::get('/finance/commissions',[FinanceCommissionController::class,'index'])->name('finance.commissions.index');

        Route::middleware('role:admin,finance')->group(function(){
            Route::get('/finance/invoices/create',[FinanceInvoiceController::class,'create'])->name('finance.invoices.create');
            Route::post('/finance/invoices',[FinanceInvoiceController::class,'store'])->name('finance.invoices.store');
            Route::post('/finance/invoices/{invoice}/issue',[FinanceInvoiceController::class,'issue'])->name('finance.invoices.issue');
            Route::post('/finance/invoices/{invoice}/void',[FinanceInvoiceController::class,'void'])->name('finance.invoices.void');
            Route::post('/finance/payments/{payment}/verify',[FinancePaymentController::class,'verify'])->name('finance.payments.verify');
            Route::post('/finance/payments/{payment}/reject',[FinancePaymentController::class,'reject'])->name('finance.payments.reject');
            Route::post('/finance/payments/{payment}/refund',[FinancePaymentController::class,'refund'])->name('finance.payments.refund');
            Route::post('/finance/commissions/{commission}/approve',[FinanceCommissionController::class,'approve'])->name('finance.commissions.approve');
            Route::post('/finance/commissions/{commission}/pay',[FinanceCommissionController::class,'pay'])->name('finance.commissions.pay');
        });

        Route::get('/finance/payments/{payment}/proof',[FinancePaymentController::class,'proof'])->name('finance.payments.proof');
        Route::get('/finance/invoices/{invoice}/print',[FinanceInvoiceController::class,'print'])->name('finance.invoices.print');
        Route::get('/finance/invoices/{invoice}',[FinanceInvoiceController::class,'show'])->name('finance.invoices.show');
        Route::post('/finance/invoices/{invoice}/manual-payments',[FinanceInvoiceController::class,'storeManualPayment'])->name('finance.invoices.manual-payment');
        Route::post('/finance/invoices/{invoice}/gateway-payments',[FinanceInvoiceController::class,'createGatewayPayment'])->name('finance.invoices.gateway-payment');
        Route::get('/pipeline',PipelineController::class)->name('pipeline');
        Route::get('/follow-ups',[FollowUpController::class,'index'])->name('follow-ups.index');Route::post('/follow-ups/{prospect}/customer-reply',[FollowUpController::class,'markCustomerReply'])->name('follow-ups.customer-reply');Route::post('/follow-ups/{prospect}/sent',[FollowUpController::class,'markSent'])->name('follow-ups.sent');Route::post('/follow-ups/{prospect}/feedback',[FollowUpController::class,'markFeedback'])->name('follow-ups.feedback');Route::post('/follow-ups/{prospect}/snooze',[FollowUpController::class,'snooze'])->name('follow-ups.snooze');Route::post('/follow-ups/{prospect}/cloud-send',[WhatsAppSendController::class,'store'])->name('follow-ups.cloud-send');
        Route::get('/targets',[SalesTargetController::class,'index'])->name('targets.index');
        Route::post('/notifications/{notification}/read',[NotificationController::class,'read'])->name('notifications.read');Route::post('/notifications/read-all',[NotificationController::class,'readAll'])->name('notifications.read-all');
        Route::middleware('role:admin')->group(function(){
            Route::post('/sales-guide/solutions',[SalesGuideController::class,'store'])->name('sales-guide.solutions.store');
            Route::put('/sales-guide/solutions/{solution}',[SalesGuideController::class,'update'])->name('sales-guide.solutions.update');
            Route::put('/targets/{user}',[SalesTargetController::class,'update'])->name('targets.update');Route::put('/follow-up-templates/{template}',[FollowUpTemplateController::class,'update'])->name('follow-up-templates.update');
            Route::get('/imports',[ImportController::class,'index'])->name('imports.index');Route::get('/imports/template',[ImportController::class,'template'])->name('imports.template');Route::get('/imports/sample',[ImportController::class,'sample'])->name('imports.sample');Route::post('/imports/preview',[ImportController::class,'preview'])->name('imports.preview');Route::post('/imports/commit',[ImportController::class,'commit'])->name('imports.commit');Route::get('/imports/{batch}',[ImportController::class,'show'])->name('imports.show');
            Route::resource('products',ProductController::class)->only(['index','store','update','destroy']);
            Route::get('/campaigns',[CampaignController::class,'index'])->name('campaigns.index');Route::post('/campaigns',[CampaignController::class,'store'])->name('campaigns.store');Route::post('/campaigns/{campaign}/send',[CampaignController::class,'send'])->name('campaigns.send');
            Route::get('/settings/business',[BusinessSettingsController::class,'index'])->name('settings.business');Route::get('/settings/whatsapp',[WhatsAppSettingsController::class,'edit'])->name('settings.whatsapp');Route::put('/settings/whatsapp',[WhatsAppSettingsController::class,'update'])->name('settings.whatsapp.update');
            Route::middleware('platform.admin')->group(function(){Route::get('/admin/clients',[ClientOnboardingController::class,'index'])->name('admin.clients.index');Route::post('/admin/clients',[ClientOnboardingController::class,'store'])->name('admin.clients.store');});
            Route::prefix('admin')->name('admin.')->group(function(){Route::resource('users',UserController::class)->except(['show','destroy']);});
        });
    });
});
