<?php
namespace App\Http\Controllers;
use App\Models\Deal;
use App\Models\Opportunity;
use App\Models\Quotation;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Inertia\Inertia;
use Inertia\Response;
class DealController extends Controller {
    public function index(Request $request):Response{$q=Deal::query()->visibleTo($request->user())->with(['prospect','owner','quotation']);if($request->filled('q')){$s=trim((string)$request->q);$q->where(fn($x)=>$x->where('deal_number','like',"%$s%")->orWhereHas('prospect',fn($p)=>$p->where('company_name','like',"%$s%")));}$rows=$q->orderByDesc('closing_date')->paginate(20)->withQueryString();$rows->through(fn($d)=>$this->payload($d));return Inertia::render('Deals/Index',['deals'=>$rows,'filters'=>$request->only(['q'])]);}
    public function createFromQuotation(Request $request,Quotation $quotation):Response{$q=$this->quotationVisible($request,$quotation);abort_unless($q->status==='accepted',422,'Quotation harus Accepted sebelum menjadi Deal.');abort_if($q->deal()->exists(),422,'Quotation ini sudah memiliki Deal.');$q->load(['prospect','opportunity']);return Inertia::render('Deals/Form',['quotation'=>['id'=>$q->id,'quotation_number'=>$q->quotation_number,'grand_total'=>(float)$q->grand_total,'prospect'=>['id'=>$q->prospect->id,'company_name'=>$q->prospect->company_name],'opportunity'=>$q->opportunity?['id'=>$q->opportunity->id,'name'=>$q->opportunity->name]:null],'deal'=>['closing_date'=>now()->format('Y-m-d'),'actual_deal_value'=>(float)$q->grand_total,'commissionable_value'=>(float)$q->grand_total,'contract_status'=>'pending','project_start_date'=>'','special_agreement'=>'','notes'=>'','schedules'=>[['label'=>'DP','percentage'=>50,'amount'=>round((float)$q->grand_total*.5,2),'trigger_type'=>'deal','due_date'=>'','notes'=>''],['label'=>'UAT','percentage'=>30,'amount'=>round((float)$q->grand_total*.3,2),'trigger_type'=>'uat','due_date'=>'','notes'=>''],['label'=>'Go-Live','percentage'=>20,'amount'=>round((float)$q->grand_total*.2,2),'trigger_type'=>'go_live','due_date'=>'','notes'=>'']]]]);}
    public function storeFromQuotation(Request $request,Quotation $quotation):RedirectResponse{$q=$this->quotationVisible($request,$quotation);abort_unless($q->status==='accepted',422,'Quotation harus Accepted.');abort_if($q->deal()->exists(),422,'Quotation ini sudah memiliki Deal.');$data=$request->validate(['closing_date'=>['required','date'],'actual_deal_value'=>['required','numeric','min:0'],'commissionable_value'=>['required','numeric','min:0','lte:actual_deal_value'],'contract_status'=>['required',Rule::in(['not_required','pending','signed'])],'project_start_date'=>['nullable','date'],'special_agreement'=>['nullable','string','max:10000'],'notes'=>['nullable','string','max:10000'],'schedules'=>['required','array','min:1'],'schedules.*.label'=>['required','string','max:255'],'schedules.*.percentage'=>['nullable','numeric','min:0','max:100'],'schedules.*.amount'=>['required','numeric','min:0'],'schedules.*.trigger_type'=>['required',Rule::in(['deal','date','uat','go_live','milestone','subscription'])],'schedules.*.due_date'=>['nullable','date'],'schedules.*.notes'=>['nullable','string','max:5000']]);$sum=(float)collect($data['schedules'])->sum('amount');abort_if(abs($sum-(float)$data['actual_deal_value'])>1,422,'Total payment schedule harus sama dengan Actual Deal Value.');$deal=DB::transaction(function()use($request,$q,$data){$number=$this->nextNumber($request->user()->organization_id);$deal=Deal::create(['organization_id'=>$request->user()->organization_id,'prospect_id'=>$q->prospect_id,'opportunity_id'=>$q->opportunity_id,'quotation_id'=>$q->id,'owner_id'=>$q->prospect->assigned_to ?: $request->user()->id,'created_by'=>$request->user()->id,'deal_number'=>$number,'status'=>'won','closing_date'=>$data['closing_date'],'quoted_value'=>$q->grand_total,'actual_deal_value'=>$data['actual_deal_value'],'commissionable_value'=>$data['commissionable_value'],'contract_status'=>$data['contract_status'],'project_start_date'=>$data['project_start_date']??null,'special_agreement'=>$data['special_agreement']??null,'notes'=>$data['notes']??null]);foreach(array_values($data['schedules']) as $i=>$row)$deal->paymentSchedules()->create(['sequence'=>$i+1,'label'=>$row['label'],'percentage'=>$row['percentage']??null,'amount'=>$row['amount'],'trigger_type'=>$row['trigger_type'],'due_date'=>$row['due_date']??null,'status'=>'scheduled','notes'=>$row['notes']??null]);$q->prospect->update(['status'=>'deal','qualification_status'=>'qualified','actual_deal_value'=>$data['actual_deal_value'],'deal_at'=>$q->prospect->deal_at?:now(),'closed_at'=>now()]);if($q->opportunity)$q->opportunity->update(['status'=>'won','stage'=>'won','closed_at'=>now()]);return$deal;});return redirect()->route('deals.show',$deal)->with('success','Deal berhasil dibuat beserta payment schedule.');}
    public function show(Request $request,Deal $deal):Response{$d=$this->visible($request,$deal);$d->load(['prospect','opportunity','quotation','owner','documents.uploader','paymentSchedules']);return Inertia::render('Deals/Show',['deal'=>$this->payload($d,true)]);}
    public function uploadDocument(Request $request,Deal $deal):RedirectResponse{$d=$this->visible($request,$deal);$data=$request->validate(['type'=>['required',Rule::in(['contract','po','spk','nda','agreement','other'])],'reference_number'=>['nullable','string','max:255'],'file'=>['required','file','max:10240','mimes:pdf,jpg,jpeg,png,doc,docx']]);$file=$request->file('file');$path=$file->store("organizations/{$request->user()->organization_id}/deals/{$d->id}",'public');$d->documents()->create(['uploaded_by'=>$request->user()->id,'type'=>$data['type'],'reference_number'=>$data['reference_number']??null,'original_name'=>$file->getClientOriginalName(),'file_path'=>$path]);return back()->with('success','Dokumen deal berhasil diupload.');}
    private function nextNumber(int $org):string{$year=now()->format('Y');$last=Deal::where('organization_id',$org)->where('deal_number','like',"DL-{$year}-%")->orderByDesc('id')->value('deal_number');$n=$last?(int)substr($last,-6)+1:1;return sprintf('DL-%s-%06d',$year,$n);}
    private function visible(Request $r,Deal $d):Deal{abort_unless(Deal::query()->visibleTo($r->user())->whereKey($d->id)->exists(),403);return$d;}
    private function quotationVisible(Request $r,Quotation $q):Quotation{abort_unless(Quotation::query()->visibleTo($r->user())->whereKey($q->id)->exists(),403);return$q;}
    private function payload(Deal $d,bool $deep=false):array{$x=['id'=>$d->id,'deal_number'=>$d->deal_number,'status'=>$d->status,'closing_date'=>$d->closing_date?->format('Y-m-d'),'quoted_value'=>(float)$d->quoted_value,'actual_deal_value'=>(float)$d->actual_deal_value,'commissionable_value'=>(float)$d->commissionable_value,'contract_status'=>$d->contract_status,'project_start_date'=>$d->project_start_date?->format('Y-m-d'),'special_agreement'=>$d->special_agreement,'notes'=>$d->notes,'prospect'=>$d->relationLoaded('prospect')&&$d->prospect?['id'=>$d->prospect->id,'company_name'=>$d->prospect->company_name]:null,'owner'=>$d->relationLoaded('owner')&&$d->owner?['id'=>$d->owner->id,'name'=>$d->owner->name]:null,'quotation'=>$d->relationLoaded('quotation')&&$d->quotation?['id'=>$d->quotation->id,'quotation_number'=>$d->quotation->quotation_number]:null,'opportunity'=>$d->relationLoaded('opportunity')&&$d->opportunity?['id'=>$d->opportunity->id,'name'=>$d->opportunity->name]:null];if($deep){$x['schedules']=$d->paymentSchedules->map(fn($s)=>['id'=>$s->id,'sequence'=>$s->sequence,'label'=>$s->label,'percentage'=>$s->percentage!==null?(float)$s->percentage:null,'amount'=>(float)$s->amount,'trigger_type'=>$s->trigger_type,'due_date'=>$s->due_date?->format('Y-m-d'),'status'=>$s->status,'notes'=>$s->notes])->values();$x['documents']=$d->documents->map(fn($f)=>['id'=>$f->id,'type'=>$f->type,'reference_number'=>$f->reference_number,'original_name'=>$f->original_name,'url'=>'/storage/'.$f->file_path,'uploaded_by'=>$f->uploader?->name,'created_at'=>$f->created_at?->toIso8601String()])->values();}return$x;}
}
