<?php
namespace App\Http\Controllers;
use App\Models\Opportunity;
use App\Models\Prospect;
use App\Models\Quotation;
use App\Models\QuotationRevision;
use App\Services\QuotationService;
use App\Services\ProspectStageService;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;
use Inertia\Inertia;
use Inertia\Response;
class QuotationController extends Controller {
    public function index(Request $request):Response{$q=Quotation::query()->visibleTo($request->user())->with(['prospect','opportunity','creator']);if($request->filled('status'))$q->where('status',$request->status);if($request->filled('q')){$s=trim((string)$request->q);$q->where(fn($x)=>$x->where('quotation_number','like',"%$s%")->orWhereHas('prospect',fn($p)=>$p->where('company_name','like',"%$s%")));}$rows=$q->latest()->paginate(20)->withQueryString();$rows->through(fn($x)=>$this->payload($x));return Inertia::render('Quotations/Index',['quotations'=>$rows,'filters'=>$request->only(['q','status']),'statuses'=>Quotation::STATUSES]);}
    public function create(Request $request):Response{$prospect=null;$opp=null;if($request->filled('opportunity_id')){$opp=Opportunity::query()->visibleTo($request->user())->with('prospect')->findOrFail((int)$request->opportunity_id);$prospect=$opp->prospect;}elseif($request->filled('prospect_id')){$prospect=Prospect::query()->visibleTo($request->user())->findOrFail((int)$request->prospect_id);}return Inertia::render('Quotations/Form',['mode'=>'create','quotation'=>['prospect_id'=>$prospect?->id,'opportunity_id'=>$opp?->id,'quotation_type'=>'project','pricing_type'=>'standard','discount_type'=>'percent','discount_value'=>0,'tax_percent'=>0,'payment_terms'=>'50% DP, 30% UAT, 20% Go-Live','project_timeline'=>'','valid_until'=>now()->addDays(14)->format('Y-m-d'),'notes'=>'','revision_reason'=>'','items'=>[['name'=>$opp?->name?:'Custom Software Development','description'=>$opp?->required_solution?:'','quantity'=>1,'unit'=>'project','unit_price'=>(float)($opp?->expected_value?:$prospect?->estimated_deal_value?:0),'discount_percent'=>0]]],'prospects'=>$this->prospects($request),'opportunities'=>$this->opportunities($request),'types'=>Quotation::TYPES]);}
    public function store(Request $request,QuotationService $service):RedirectResponse{$data=$this->validateData($request);$prospect=Prospect::query()->visibleTo($request->user())->findOrFail($data['prospect_id']);if(!empty($data['opportunity_id']))Opportunity::query()->visibleTo($request->user())->where('prospect_id',$prospect->id)->findOrFail($data['opportunity_id']);$tot=$service->totals($data['items'],$data['discount_type'],(float)$data['discount_value'],(float)$data['tax_percent']);$required=$service->approvalRequired($data,$tot);$q=DB::transaction(function()use($request,$data,$prospect,$tot,$required,$service){$q=Quotation::create([...collect($data)->except(['items','revision_reason'])->all(),'organization_id'=>$request->user()->organization_id,'created_by'=>$request->user()->id,'quotation_number'=>$service->nextNumber($request->user()->organization_id),'revision_number'=>1,'status'=>$required?'pending_approval':'draft','requires_approval'=>$required,'approval_status'=>$required?'pending':'not_required','subtotal'=>$tot['subtotal'],'discount_amount'=>$tot['discount_amount'],'tax_amount'=>$tot['tax_amount'],'grand_total'=>$tot['grand_total']]);$q->items()->createMany($tot['items']);return$q;});return redirect()->route('quotations.show',$q)->with('success',$required?'Quotation dibuat dan menunggu approval.':'Quotation draft berhasil dibuat.');}
    public function show(Request $request,Quotation $quotation):Response{$q=$this->visible($request,$quotation);$q->load(['prospect.assignedUser','opportunity','creator','approver','items','revisions.creator','deal']);return Inertia::render('Quotations/Show',['quotation'=>$this->payload($q,true)]);}
    public function edit(Request $request,Quotation $quotation):Response{$q=$this->visible($request,$quotation);abort_if(in_array($q->status,['accepted','cancelled'],true),422,'Quotation final tidak dapat diedit.');$q->load('items');return Inertia::render('Quotations/Form',['mode'=>'edit','quotation'=>[...$this->payload($q,true),'revision_reason'=>''],'prospects'=>$this->prospects($request),'opportunities'=>$this->opportunities($request),'types'=>Quotation::TYPES]);}
    public function update(Request $request,Quotation $quotation,QuotationService $service):RedirectResponse{$q=$this->visible($request,$quotation);abort_if(in_array($q->status,['accepted','cancelled'],true),422,'Quotation final tidak dapat diedit.');$data=$this->validateData($request,true);$prospect=Prospect::query()->visibleTo($request->user())->findOrFail($data['prospect_id']);if(!empty($data['opportunity_id']))Opportunity::query()->visibleTo($request->user())->where('prospect_id',$prospect->id)->findOrFail($data['opportunity_id']);$tot=$service->totals($data['items'],$data['discount_type'],(float)$data['discount_value'],(float)$data['tax_percent']);$required=$service->approvalRequired($data,$tot);DB::transaction(function()use($q,$request,$data,$tot,$required,$service){$service->saveRevision($q,$request->user(),$data['revision_reason']??'Revision');$next=$q->revision_number+1;$q->update([...collect($data)->except(['items','revision_reason'])->all(),'revision_number'=>$next,'status'=>$required?'pending_approval':'draft','requires_approval'=>$required,'approval_status'=>$required?'pending':'not_required','approved_by'=>null,'approved_at'=>null,'subtotal'=>$tot['subtotal'],'discount_amount'=>$tot['discount_amount'],'tax_amount'=>$tot['tax_amount'],'grand_total'=>$tot['grand_total']]);$q->items()->delete();$q->items()->createMany($tot['items']);});return redirect()->route('quotations.show',$q)->with('success','Quotation direvisi menjadi Rev.'.$q->fresh()->revision_number.'.');}
    public function approve(Request $request,Quotation $quotation):RedirectResponse{$q=$this->visible($request,$quotation);abort_unless($request->user()->isAdmin(),403);abort_unless($q->status==='pending_approval',422,'Quotation tidak menunggu approval.');$q->update(['status'=>'approved','approval_status'=>'approved','approved_by'=>$request->user()->id,'approved_at'=>now()]);return back()->with('success','Quotation disetujui.');}
    public function send(Request $request,Quotation $quotation):RedirectResponse{$q=$this->visible($request,$quotation);abort_if($q->requires_approval&&$q->approval_status!=='approved',422,'Quotation harus di-approve sebelum dikirim.');abort_unless(in_array($q->status,['draft','approved','sent','viewed'],true),422,'Status quotation tidak dapat dikirim.');$q->update(['status'=>'sent','sent_at'=>now()]);return back()->with('success','Quotation ditandai telah dikirim ke client.');}
    public function accept(Request $request,Quotation $quotation,ProspectStageService $stages):RedirectResponse{$q=$this->visible($request,$quotation);abort_unless(in_array($q->status,['sent','viewed','approved'],true),422,'Quotation belum siap diterima.');$q->update(['status'=>'accepted','accepted_at'=>now(),'rejected_at'=>null]);if($q->opportunity)$q->opportunity->update(['stage'=>'won','status'=>'won','closed_at'=>now()]);$q->prospect->update(['qualification_status'=>'qualified']);$stages->transition($q->prospect,'deal',$request->user(),'Quotation accepted');return back()->with('success','Quotation diterima. Silakan buat Deal dan payment schedule.');}
    public function reject(Request $request,Quotation $quotation):RedirectResponse{$q=$this->visible($request,$quotation);$q->update(['status'=>'rejected','rejected_at'=>now()]);return back()->with('success','Quotation ditandai ditolak.');}
    public function print(Request $request,Quotation $quotation):Response{$q=$this->visible($request,$quotation);$q->load(['organization','prospect','items']);return Inertia::render('Quotations/Print',['quotation'=>$this->payload($q,true),'organization'=>['name'=>$q->organization->name,'contact_email'=>$q->organization->contact_email,'contact_phone'=>$q->organization->contact_phone,'address'=>$q->organization->address]]);}
    private function validateData(Request $request,bool $revision=false):array{$org=$request->user()->organization_id;return$request->validate(['prospect_id'=>['required',Rule::exists('prospects','id')->where(fn($q)=>$q->where('organization_id',$org))],'opportunity_id'=>['nullable',Rule::exists('opportunities','id')->where(fn($q)=>$q->where('organization_id',$org))],'quotation_type'=>['required',Rule::in(array_keys(Quotation::TYPES))],'pricing_type'=>['required',Rule::in(['standard','custom'])],'discount_type'=>['required',Rule::in(['percent','fixed'])],'discount_value'=>['nullable','numeric','min:0'],'tax_percent'=>['nullable','numeric','min:0','max:100'],'payment_terms'=>['nullable','string','max:5000'],'project_timeline'=>['nullable','string','max:255'],'valid_until'=>['nullable','date'],'notes'=>['nullable','string','max:10000'],'revision_reason'=>[$revision?'required':'nullable','string','max:255'],'items'=>['required','array','min:1'],'items.*.name'=>['required','string','max:255'],'items.*.description'=>['nullable','string','max:5000'],'items.*.quantity'=>['required','numeric','min:0.01'],'items.*.unit'=>['required','string','max:50'],'items.*.unit_price'=>['required','numeric','min:0'],'items.*.discount_percent'=>['nullable','numeric','min:0','max:100']]);}
    private function visible(Request $r,Quotation $q):Quotation{abort_unless(Quotation::query()->visibleTo($r->user())->whereKey($q->id)->exists(),403);return$q;}
    private function prospects(Request $r):array{return Prospect::query()->visibleTo($r->user())->orderBy('company_name')->get(['id','company_name'])->toArray();}
    private function opportunities(Request $r):array{return Opportunity::query()->visibleTo($r->user())->where('status','open')->with('prospect:id,company_name')->orderByDesc('updated_at')->get()->map(fn($o)=>['id'=>$o->id,'prospect_id'=>$o->prospect_id,'name'=>$o->name,'company_name'=>$o->prospect?->company_name,'expected_value'=>(float)$o->expected_value])->all();}
    private function payload(Quotation $q,bool $deep=false):array{$d=['id'=>$q->id,'prospect_id'=>$q->prospect_id,'opportunity_id'=>$q->opportunity_id,'quotation_number'=>$q->quotation_number,'revision_number'=>$q->revision_number,'quotation_type'=>$q->quotation_type,'status'=>$q->status,'status_label'=>$q->status_label,'pricing_type'=>$q->pricing_type,'currency'=>$q->currency,'subtotal'=>(float)$q->subtotal,'discount_type'=>$q->discount_type,'discount_value'=>(float)$q->discount_value,'discount_amount'=>(float)$q->discount_amount,'tax_percent'=>(float)$q->tax_percent,'tax_amount'=>(float)$q->tax_amount,'grand_total'=>(float)$q->grand_total,'payment_terms'=>$q->payment_terms,'project_timeline'=>$q->project_timeline,'valid_until'=>$q->valid_until?->format('Y-m-d'),'notes'=>$q->notes,'requires_approval'=>(bool)$q->requires_approval,'approval_status'=>$q->approval_status,'approved_at'=>$q->approved_at?->toIso8601String(),'sent_at'=>$q->sent_at?->toIso8601String(),'accepted_at'=>$q->accepted_at?->toIso8601String(),'prospect'=>$q->relationLoaded('prospect')&&$q->prospect?['id'=>$q->prospect->id,'company_name'=>$q->prospect->company_name,'contact_name'=>$q->prospect->contact_name,'email'=>$q->prospect->email,'phone'=>$q->prospect->phone,'address'=>$q->prospect->city]:null,'opportunity'=>$q->relationLoaded('opportunity')&&$q->opportunity?['id'=>$q->opportunity->id,'name'=>$q->opportunity->name]:null,'creator'=>$q->relationLoaded('creator')&&$q->creator?['id'=>$q->creator->id,'name'=>$q->creator->name]:null,'approver'=>$q->relationLoaded('approver')&&$q->approver?['id'=>$q->approver->id,'name'=>$q->approver->name]:null,'has_deal'=>$q->relationLoaded('deal')&&$q->deal!==null,'deal_id'=>$q->relationLoaded('deal')?$q->deal?->id:null];if($deep){$d['items']=$q->items->map(fn($i)=>['id'=>$i->id,'name'=>$i->name,'description'=>$i->description,'quantity'=>(float)$i->quantity,'unit'=>$i->unit,'unit_price'=>(float)$i->unit_price,'discount_percent'=>(float)$i->discount_percent,'line_total'=>(float)$i->line_total])->values();$d['revisions']=$q->relationLoaded('revisions')?$q->revisions->map(fn($r)=>['id'=>$r->id,'revision_number'=>$r->revision_number,'reason'=>$r->reason,'created_at'=>$r->created_at?->toIso8601String(),'created_by'=>$r->creator?->name])->values():[];}return$d;}
}
