import { Head, Link, router, usePage } from '@inertiajs/react';
import AppLayout from '../../Layouts/AppLayout';
import Icon from '../../Components/Icon';
import { money, dateTime } from '../../Utils/format';
export default function Show({quotation:q}){const {auth}=usePage().props;const post=(action,msg)=>confirm(msg)&&router.post(`/quotations/${q.id}/${action}`,{}, {preserveScroll:true});return <AppLayout title={`${q.quotation_number} · Rev.${q.revision_number}`} subtitle={q.prospect?.company_name||'Quotation'} action={<div className="action-group"><Link href="/quotations" className="btn btn-secondary"><Icon name="arrowLeft" size={17}/>Kembali</Link><Link href={`/quotations/${q.id}/print`} className="btn btn-soft" target="_blank"><Icon name="eye" size={16}/>Preview / PDF</Link>{!['accepted','cancelled'].includes(q.status)&&<Link href={`/quotations/${q.id}/edit`} className="btn btn-primary"><Icon name="edit" size={16}/>Revision</Link>}</div>}><Head title={q.quotation_number}/>
<section className="commercial-hero panel"><div><span className={`badge ${q.status==='accepted'?'badge-success':q.status==='pending_approval'?'badge-warning':q.status==='rejected'?'badge-danger':'badge-info'}`}>{q.status_label}</span><h2>{q.prospect?.company_name}</h2><p>{q.opportunity?.name||'Direct quotation'} · {q.quotation_type}</p></div><div><small>Grand Total</small><strong>{money(q.grand_total)}</strong><span>Valid until {q.valid_until||'—'}</span></div></section>
<div className="detail-layout"><div className="detail-main"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Quotation Items</span><h3>Scope & pricing</h3></div></div><div className="clean-table-wrap"><table className="clean-table"><thead><tr><th>Item</th><th>Qty</th><th>Unit Price</th><th>Disc.</th><th>Total</th></tr></thead><tbody>{q.items.map(i=><tr key={i.id}><td><strong>{i.name}</strong><small className="cell-sub">{i.description||''}</small></td><td>{i.quantity} {i.unit}</td><td>{money(i.unit_price)}</td><td>{i.discount_percent}%</td><td>{money(i.line_total)}</td></tr>)}</tbody></table></div><div className="quotation-totals"><div><span>Subtotal</span><b>{money(q.subtotal)}</b></div><div><span>Discount</span><b>- {money(q.discount_amount)}</b></div><div><span>Tax ({q.tax_percent}%)</span><b>{money(q.tax_amount)}</b></div><div className="grand"><span>Grand Total</span><b>{money(q.grand_total)}</b></div></div></section>
<section className="panel"><div className="panel-head"><div><span className="eyebrow">Terms</span><h3>Commercial terms</h3></div></div><div className="commercial-detail-grid"><div><span>Payment Terms</span><p>{q.payment_terms||'—'}</p></div><div><span>Project Timeline</span><p>{q.project_timeline||'—'}</p></div><div><span>Pricing Type</span><p>{q.pricing_type}</p></div><div><span>Approval</span><p>{q.approval_status}</p></div><div className="span-2"><span>Notes</span><p>{q.notes||'—'}</p></div></div></section>
<section className="panel"><div className="panel-head"><div><span className="eyebrow">Revision History</span><h3>Riwayat penawaran</h3></div></div>{q.revisions?.length?<div className="commercial-list">{q.revisions.map(r=><div key={r.id}><div><strong>Rev.{r.revision_number}</strong><small>{r.reason||'Revision'} · {r.created_by||'System'} · {dateTime(r.created_at)}</small></div></div>)}</div>:<div className="mini-empty">Belum ada revision sebelumnya.</div>}</section></div>
<aside className="detail-side"><section className="panel sticky-panel"><span className="eyebrow">Actions</span><h3 className="side-title">Quotation lifecycle</h3>{q.status==='pending_approval'&&auth.user.is_admin&&<button className="btn btn-primary btn-block" onClick={()=>post('approve','Approve quotation ini?')}>Approve</button>}{['draft','approved','sent','viewed'].includes(q.status)&&<button className="btn btn-soft btn-block" onClick={()=>post('send','Tandai quotation sudah dikirim?')}>Mark as Sent</button>}{['sent','viewed','approved'].includes(q.status)&&<><button className="btn btn-primary btn-block" onClick={()=>post('accept','Tandai client menerima quotation?')}>Accepted</button><button className="btn btn-danger-soft btn-block" onClick={()=>post('reject','Tandai quotation ditolak?')}>Rejected</button></>}{q.status==='accepted'&&!q.has_deal&&<Link href={`/deals/from-quotation/${q.id}`} className="btn btn-primary btn-block">Create Deal</Link>}{q.has_deal&&<Link href={`/deals/${q.deal_id}`} className="btn btn-soft btn-block">Open Deal</Link>}<div className="source-box"><span>Created by</span><strong>{q.creator?.name||'—'}</strong>{q.approver&&<small>Approved by {q.approver.name}</small>}</div></section></aside></div>
</AppLayout>}
