import { Head, Link, useForm } from '@inertiajs/react';
import { useMemo, useState } from 'react';
import AppLayout from '../../Layouts/AppLayout';
import Icon from '../../Components/Icon';
import { Badge } from '../../Components/Ui';
import { money } from '../../Utils/format';

function Field({label,help,error,span=false,children}){return <label className={`field ${span?'span-2':''}`}><span>{label}</span>{help&&<small className="field-help">{help}</small>}{children}{error&&<small className="field-error">{error}</small>}</label>}
const blankItem=()=>({solution_catalog_item_id:null,name:'',description:'',quantity:1,unit:'project',unit_price:0,internal_cost_snapshot:null,recommended_price_snapshot:null,minimum_price_snapshot:null,discount_percent:0});

function PricebookDrawer({items,onAdd,onClose}){
    const [q,setQ]=useState('');
    const filtered=useMemo(()=>items.filter(x=>`${x.name} ${x.category} ${x.code}`.toLowerCase().includes(q.toLowerCase())),[items,q]);
    return <div className="sv-drawer-backdrop" onClick={onClose}><aside className="sv-pricebook-drawer" onClick={e=>e.stopPropagation()}><div className="sv-drawer-head"><div><span className="eyebrow">Internal Solution Pricebook</span><h3>Tambah item quotation</h3><p>Cost hanya referensi internal; quotation memakai selling price.</p></div><button className="icon-button" onClick={onClose}><Icon name="close" size={19}/></button></div><div className="search-box"><Icon name="search" size={17}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari Create Order, Tracking, API..."/></div><div className="sv-drawer-list">{filtered.map(item=><article key={item.id}><div className="sv-drawer-item-head"><span>{item.category}</span><Badge tone={Number(item.recommended_price)>0?'success':'warning'}>{Number(item.recommended_price)>0?'Ready':'Set price'}</Badge></div><h4>{item.name}</h4><p>{item.description}</p><div className="sv-pricebook-numbers"><span><small>Cost</small><strong>{Number(item.internal_cost)>0?money(item.internal_cost):'—'}</strong></span><span><small>Recommended</small><strong>{Number(item.recommended_price)>0?money(item.recommended_price):'—'}</strong></span><span><small>Minimum</small><strong>{item.minimum_price?money(item.minimum_price):'—'}</strong></span></div>{item.upsell_notes&&<em>{item.upsell_notes}</em>}<button className="btn btn-primary btn-sm" onClick={()=>onAdd(item)}>Tambah ke quotation</button></article>)}{!filtered.length&&<div className="mini-empty">Tidak ada solution yang cocok.</div>}</div></aside></div>;
}

export default function Form({mode,quotation,prospects,opportunities,types,solutionCatalog=[]}){
    const editing=mode==='edit';const [drawer,setDrawer]=useState(false);
    const f=useForm({prospect_id:quotation.prospect_id||'',opportunity_id:quotation.opportunity_id||'',quotation_type:quotation.quotation_type||'project',pricing_type:quotation.pricing_type||'standard',discount_type:quotation.discount_type||'percent',discount_value:quotation.discount_value??0,tax_percent:quotation.tax_percent??0,payment_terms:quotation.payment_terms||'',project_timeline:quotation.project_timeline||'',valid_until:quotation.valid_until||'',notes:quotation.notes||'',revision_reason:quotation.revision_reason||'',items:(quotation.items?.length?quotation.items:[blankItem()]).map(i=>({...blankItem(),...i}))});
    const setItem=(idx,key,val)=>f.setData('items',f.data.items.map((it,i)=>i===idx?{...it,[key]:val}:it));
    const addBlank=()=>f.setData('items',[...f.data.items,blankItem()]);
    const addCatalog=(item)=>{f.setData('items',[...f.data.items.filter((x,i)=>!(f.data.items.length===1&&i===0&&!x.name&&Number(x.unit_price)===0)),{solution_catalog_item_id:item.id,name:item.name,description:item.description||'',quantity:1,unit:item.unit||'project',unit_price:Number(item.recommended_price||0),internal_cost_snapshot:Number(item.internal_cost||0),recommended_price_snapshot:Number(item.recommended_price||0),minimum_price_snapshot:item.minimum_price==null?null:Number(item.minimum_price),discount_percent:0}]);setDrawer(false)};
    const remove=idx=>f.data.items.length>1&&f.setData('items',f.data.items.filter((_,i)=>i!==idx));
    const subtotal=f.data.items.reduce((sum,i)=>{const base=Number(i.quantity||0)*Number(i.unit_price||0);return sum+base-(base*Number(i.discount_percent||0)/100)},0);
    const disc=f.data.discount_type==='fixed'?Math.min(subtotal,Number(f.data.discount_value||0)):subtotal*Number(f.data.discount_value||0)/100;const after=Math.max(0,subtotal-disc);const tax=after*Number(f.data.tax_percent||0)/100;const total=after+tax;
    const internalCost=f.data.items.reduce((sum,i)=>sum+Number(i.quantity||0)*Number(i.internal_cost_snapshot||0),0);
    const submit=e=>{e.preventDefault();editing?f.put(`/quotations/${quotation.id}`):f.post('/quotations')};

    return <AppLayout title={editing?`Edit ${quotation.quotation_number}`:'Buat Quotation'} subtitle="Pilih solution dari internal pricebook atau tambahkan custom item setelah discovery." action={<div className="action-group"><Link href="/sales-guide#solution-pricebook" className="btn btn-soft">Pricebook</Link><Link href={editing?`/quotations/${quotation.id}`:'/quotations'} className="btn btn-secondary"><Icon name="arrowLeft" size={17}/>Kembali</Link></div>}><Head title={editing?'Edit Quotation':'Buat Quotation'}/>
        <section className="sv-context-banner"><span className="sv-context-icon"><Icon name="spark" size={19}/></span><div><strong>Bagaimana mengisi item?</strong><p>Pilih dari Pricebook untuk extension standar. Gunakan Custom Item hanya untuk scope bespoke. Internal cost membantu Sales memahami margin dan tidak muncul di dokumen client.</p></div></section>
        <form onSubmit={submit} className="form-layout"><div className="form-main">
            <section className="panel form-section"><div className="section-head"><span className="section-number">01</span><div><h3>Client & Opportunity</h3><p>Opportunity direkomendasikan agar quotation punya konteks discovery.</p></div></div><div className="form-grid"><Field label="Prospek *" error={f.errors.prospect_id}><select value={f.data.prospect_id} onChange={e=>f.setData('prospect_id',e.target.value)}><option value="">Pilih prospek</option>{prospects.map(p=><option key={p.id} value={p.id}>{p.company_name}</option>)}</select></Field><Field label="Opportunity" help="Jika dipilih, prospect akan disinkronkan otomatis."><select value={f.data.opportunity_id} onChange={e=>{const id=e.target.value;f.setData('opportunity_id',id);const o=opportunities.find(x=>String(x.id)===String(id));if(o&&String(f.data.prospect_id)!==String(o.prospect_id))f.setData('prospect_id',o.prospect_id)}}><option value="">Tanpa opportunity</option>{opportunities.map(o=><option key={o.id} value={o.id}>{o.company_name} · {o.name}</option>)}</select></Field><Field label="Quotation Type"><select value={f.data.quotation_type} onChange={e=>f.setData('quotation_type',e.target.value)}>{Object.entries(types).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Pricing"><select value={f.data.pricing_type} onChange={e=>f.setData('pricing_type',e.target.value)}><option value="standard">Standard / Pricebook</option><option value="custom">Custom Pricing (approval)</option></select></Field></div></section>

            <section className="panel form-section"><div className="panel-head"><div><span className="eyebrow">02 · Commercial items</span><h3>Solution yang dijual</h3><p>Harga jual boleh disesuaikan, tetapi price floor dapat memicu approval.</p></div><div className="action-group"><button type="button" className="btn btn-primary" onClick={()=>setDrawer(true)}><Icon name="plus" size={15}/>Dari Pricebook</button><button type="button" className="btn btn-soft" onClick={addBlank}>Custom Item</button></div></div>
                <div className="quote-items sv-quote-items">{f.data.items.map((it,idx)=>{const floor=Number(it.minimum_price_snapshot||0);const below=floor>0&&Number(it.unit_price||0)<floor;return <div className={`quote-item sv-quote-item ${below?'below-floor':''}`} key={idx}><div className="quote-item-head"><div><strong>{it.name||`Custom Item ${idx+1}`}</strong>{it.solution_catalog_item_id?<span className="sv-source-chip">Pricebook</span>:<span className="sv-source-chip custom">Custom</span>}</div><button type="button" className="icon-button" onClick={()=>remove(idx)}><Icon name="trash" size={15}/></button></div>
                    {it.solution_catalog_item_id&&<div className="sv-internal-reference"><span><small>Internal cost</small><strong>{money(it.internal_cost_snapshot)}</strong></span><span><small>Recommended</small><strong>{money(it.recommended_price_snapshot)}</strong></span><span><small>Minimum</small><strong>{it.minimum_price_snapshot?money(it.minimum_price_snapshot):'—'}</strong></span>{below&&<b>Di bawah minimum → perlu approval</b>}</div>}
                    <div className="form-grid"><Field label="Service / Product"><input value={it.name} onChange={e=>setItem(idx,'name',e.target.value)}/></Field><Field label="Unit"><input value={it.unit} onChange={e=>setItem(idx,'unit',e.target.value)}/></Field><Field label="Qty"><input type="number" min="0.01" step="0.01" value={it.quantity} onChange={e=>setItem(idx,'quantity',e.target.value)}/></Field><Field label="Selling Price"><input type="number" min="0" value={it.unit_price} onChange={e=>setItem(idx,'unit_price',e.target.value)}/><small className="field-hint">{money(it.unit_price)}</small></Field><Field label="Item Discount %"><input type="number" min="0" max="100" value={it.discount_percent} onChange={e=>setItem(idx,'discount_percent',e.target.value)}/></Field><Field label="Line Total"><input disabled value={money((Number(it.quantity||0)*Number(it.unit_price||0))*(1-Number(it.discount_percent||0)/100))}/></Field><Field label="Description / Scope" span><textarea rows="2" value={it.description||''} onChange={e=>setItem(idx,'description',e.target.value)}/></Field></div></div>})}</div>{f.errors.items&&<small className="field-error">{f.errors.items}</small>}
            </section>

            <section className="panel form-section"><div className="section-head"><span className="section-number">03</span><div><h3>Commercial Terms</h3><p>Discount, pajak, validity, timeline dan payment terms.</p></div></div><div className="form-grid"><Field label="Discount Type"><select value={f.data.discount_type} onChange={e=>f.setData('discount_type',e.target.value)}><option value="percent">Percent</option><option value="fixed">Fixed Nominal</option></select></Field><Field label="Discount"><input type="number" min="0" value={f.data.discount_value} onChange={e=>f.setData('discount_value',e.target.value)}/></Field><Field label="Tax %"><input type="number" min="0" max="100" step="0.01" value={f.data.tax_percent} onChange={e=>f.setData('tax_percent',e.target.value)}/></Field><Field label="Valid Until"><input type="date" value={f.data.valid_until} onChange={e=>f.setData('valid_until',e.target.value)}/></Field><Field label="Project Timeline"><input value={f.data.project_timeline} onChange={e=>f.setData('project_timeline',e.target.value)} placeholder="6-8 weeks"/></Field><Field label="Payment Terms"><input value={f.data.payment_terms} onChange={e=>f.setData('payment_terms',e.target.value)} placeholder="50% DP, 30% UAT, 20% Go-Live"/></Field><Field label="Notes" span><textarea rows="3" value={f.data.notes} onChange={e=>f.setData('notes',e.target.value)}/></Field>{editing&&<Field label="Revision Reason *" span error={f.errors.revision_reason}><input value={f.data.revision_reason} onChange={e=>f.setData('revision_reason',e.target.value)} placeholder="Scope / price / terms adjustment"/></Field>}</div></section>
        </div><aside className="form-side"><section className="panel quote-summary sv-quote-summary"><span className="eyebrow">Internal summary</span><div><span>Reference Cost</span><strong>{money(internalCost)}</strong></div><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><div><span>Discount</span><strong>- {money(disc)}</strong></div><div><span>Tax</span><strong>{money(tax)}</strong></div><div className="quote-summary-total"><span>Grand Total</span><strong>{money(total)}</strong></div>{subtotal>0&&<p>Estimated gross margin before overhead: <b>{Math.round((subtotal-internalCost)/subtotal*100)}%</b></p>}<p>Approval diwajibkan untuk custom pricing, discount &gt;5%, total ≥ Rp50 juta, atau selling price di bawah minimum pricebook.</p></section><button className="btn btn-primary btn-block btn-lg" disabled={f.processing}>{f.processing?'Menyimpan...':editing?'Simpan Revision':'Buat Quotation'}</button>{Object.values(f.errors).length>0&&<small className="field-error">{Object.values(f.errors)[0]}</small>}</aside></form>
        {drawer&&<PricebookDrawer items={solutionCatalog} onAdd={addCatalog} onClose={()=>setDrawer(false)}/>} 
    </AppLayout>;
}
