import { Head } from '@inertiajs/react';
import { useCallback, useMemo, useRef, useState } from 'react';
import AppLayout from '../../Layouts/AppLayout';
import usePaymentStream from '../../Hooks/usePaymentStream';
import csrfFetch from '../../Utils/csrfFetch';

const money=(v)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0));
const date=(v)=>v?new Date(v).toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'}):'—';
const resourceLabel={users:'User aktif',prospects:'Prospek'};
const methodIcon={va:'🏦',qris:'◆',ewallet:'◈',cstore:'▤',cc:'◇',paylater:'◌'};

export default function Addons({subscription,entitlements={},addons=[],orders=[],paymentChannels=[],gateway={},maxUnits=20}){
 const availableMethods=useMemo(()=>paymentChannels.map(m=>({...m,channels:(m.channels||[]).filter(c=>c.feature_status!=='inactive'&&c.health_status!=='offline')})).filter(m=>m.channels.length),[paymentChannels]);
 const [selectedKey,setSelectedKey]=useState(addons[0]?.key||'');
 const [units,setUnits]=useState(1);
 const [method,setMethod]=useState(availableMethods[0]?.code||'va');
 const currentMethod=availableMethods.find(m=>m.code===method)||availableMethods[0];
 const [channel,setChannel]=useState(currentMethod?.channels?.[0]?.code||'bca');
 const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [session,setSession]=useState(null); const popup=useRef(null);
 const selected=addons.find(a=>a.key===selectedKey)||addons[0];
 const total=Number(selected?.current_price||0)*Number(units||1);
 const added=Number(selected?.resource_quantity||0)*Number(units||1);
 const onComplete=useCallback(()=>window.setTimeout(()=>{window.location.href='/subscription/addons';},1200),[]);
 const {payment,connection}=usePaymentStream({reference:session?.reference,streamUrl:session?.stream_url,statusUrl:session?.status_url,initialStatus:'pending',onComplete});
 const chooseMethod=(item)=>{setMethod(item.code);setChannel(item.channels?.[0]?.code||'');};
 const buy=async()=>{if(!selected||busy||!method||!channel)return;setBusy(true);setError('');const w=window.open('','ipaymu-addon-payment');popup.current=w;if(w){w.document.title='Connecting to iPaymu';w.document.body.innerHTML='<div style="font-family:system-ui;padding:40px">Menyiapkan pembayaran add-on…</div>';}try{const r=await csrfFetch('/subscription/addons/pay',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({addon_key:selected.key,units:Number(units),payment_method:method,payment_channel:channel})});const d=await r.json();if(!r.ok)throw new Error(d.message||Object.values(d.errors||{})?.[0]?.[0]||'Tidak dapat membuat pembayaran add-on.');setSession(d);if(w)w.location.href=d.checkout_url;else window.location.href=d.checkout_url;}catch(e){try{w?.close();}catch{}setError(e.message||'Pembayaran gagal disiapkan.');}finally{setBusy(false);}};
 const userCap=entitlements?.limits?.users; const prospectCap=entitlements?.limits?.prospects;
 return <AppLayout title="Subscription Add-ons" subtitle="Tambah kapasitas tanpa mengganti paket utama."><Head title="Subscription Add-ons"/>
  <section className="addon-hero"><div><span>ACTIVE SUBSCRIPTION</span><h2>{subscription?.plan?.name} · {subscription?.billing_cycle}</h2><p>Co-term sampai {date(subscription?.ends_at)}. Add-on aktif setelah pembayaran iPaymu terverifikasi.</p></div><div className="addon-capacity"><span><small>User aktif</small><strong>{userCap?.unlimited?'Unlimited':`${userCap?.used||0} / ${userCap?.limit||0}`}</strong></span><span><small>Prospek</small><strong>{prospectCap?.unlimited?'Unlimited':`${Number(prospectCap?.used||0).toLocaleString('id-ID')} / ${Number(prospectCap?.limit||0).toLocaleString('id-ID')}`}</strong></span></div></section>
  <div className="addon-layout"><main className="addon-catalog"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Capacity add-ons</span><h3>Pilih tambahan kapasitas</h3><p>Harga mengikuti billing cycle subscription aktif.</p></div></div><div className="addon-grid">{addons.map(a=><button type="button" key={a.key} className={`addon-card ${selectedKey===a.key?'active':''}`} onClick={()=>{setSelectedKey(a.key);setUnits(1);}}><span>{resourceLabel[a.resource_key]||a.resource_key}</span><h3>{a.name}</h3><p>{a.description}</p><strong>{money(a.current_price)} <small>/{subscription?.billing_cycle==='annual'?'tahun':'bulan'}</small></strong><em>+{Number(a.resource_quantity).toLocaleString('id-ID')} {resourceLabel[a.resource_key]||a.resource_key}</em></button>)}</div></section>
  <section className="panel"><div className="panel-head"><div><span className="eyebrow">Payment method</span><h3>Bayar via iPaymu</h3></div></div><div className="addon-methods">{availableMethods.map(m=><button type="button" key={m.code} className={method===m.code?'active':''} onClick={()=>chooseMethod(m)}><i>{methodIcon[m.code]||'◇'}</i><span><strong>{m.name}</strong><small>{m.description}</small></span></button>)}</div>{currentMethod&&<div className="addon-channels">{currentMethod.channels.map(c=><button type="button" key={c.code} className={channel===c.code?'active':''} onClick={()=>setChannel(c.code)}><strong>{c.name}</strong><small>{c.health_status}</small></button>)}</div>}</section>
  <section className="panel"><div className="panel-head"><div><span className="eyebrow">History</span><h3>Riwayat add-on</h3></div></div><div className="addon-history">{orders.length?orders.map(o=><article key={o.id}><div><strong>{o.addon?.name||'Add-on'}</strong><small>{o.units} paket · +{Number(o.resource_quantity).toLocaleString('id-ID')} {resourceLabel[o.resource_key]||o.resource_key}</small></div><div><b>{money(o.total_amount)}</b><span className={`badge ${o.status==='activated'?'badge-success':o.status==='pending_verification'?'badge-warning':o.status==='failed'?'badge-danger':'badge-info'}`}>{o.status}</span></div></article>):<div className="mini-empty">Belum ada pembelian add-on.</div>}</div></section></main>
  <aside className="addon-summary panel"><span className="eyebrow">ORDER SUMMARY</span><h2>{selected?.name||'Pilih add-on'}</h2><p>{selected?.description}</p><label><span>Jumlah paket</span><div className="addon-stepper"><button type="button" onClick={()=>setUnits(Math.max(1,units-1))}>−</button><strong>{units}</strong><button type="button" onClick={()=>setUnits(Math.min(maxUnits,units+1))}>+</button></div></label><div className="addon-summary-lines"><span><em>Tambahan kapasitas</em><b>+{added.toLocaleString('id-ID')} {resourceLabel[selected?.resource_key]||selected?.resource_key}</b></span><span><em>Harga / paket</em><b>{money(selected?.current_price)}</b></span><span className="total"><em>Total</em><b>{money(total)}</b></span></div><button className="btn btn-primary btn-block" disabled={!gateway.configured||busy||!selected||Boolean(session&&!payment.active)} onClick={buy}>{busy?'Menghubungkan iPaymu…':session&&!payment.active?'Menunggu pembayaran…':'Beli Add-on'}</button>{error&&<p className="field-error">{error}</p>}{session&&<div className={`addon-live ${payment.active?'done':''}`}><strong>{payment.active?'Add-on aktif':'Pembayaran dipantau realtime'}</strong><small>{connection}</small>{session.checkout_url&&<a href={session.checkout_url} target="_blank" rel="noreferrer">Buka pembayaran ↗</a>}</div>}<small className="addon-note">Masa berlaku mengikuti subscription aktif. Proration belum diterapkan pada Batch 5C.</small></aside></div>
 </AppLayout>;
}
