import { useForm } from '@inertiajs/react';
import PublicShell from './PublicShell';
const rupiah=v=>`Rp ${Number(v||0).toLocaleString('id-ID')}`;
export default function Checkout({ subscription, plans, configurations, support }) {
 const selection=useForm({plan_key:subscription?.plan?.key||plans[0]?.key||'starter',configuration_key:subscription?.business_configuration?.key||configurations[0]?.key||'software-agency',billing_cycle:subscription?.billing_cycle||'monthly'});
 const pay=useForm({payment_method:'va',payment_channel:'bca'});
 const update=e=>{e.preventDefault();selection.patch('/subscription/checkout',{preserveScroll:true});};
 const checkout=e=>{e.preventDefault();pay.post('/subscription/pay');};
 return <PublicShell title="Checkout Subscription"><section className="sv-public-hero compact"><span>/ CHECKOUT</span><h1>Aktifkan workspace<br/><em>melalui iPaymu.</em></h1><p>Konfigurasi bisnis baru aktif setelah callback pembayaran tervalidasi.</p></section><div className="sv-checkout-grid"><form className="sv-register-card" onSubmit={update}><h2>Paket & konfigurasi</h2><label>Paket<select value={selection.data.plan_key} onChange={e=>selection.setData('plan_key',e.target.value)}>{plans.map(x=><option value={x.key} key={x.key}>{x.name}</option>)}</select></label><label>Konfigurasi<select value={selection.data.configuration_key} onChange={e=>selection.setData('configuration_key',e.target.value)}>{configurations.map(x=><option value={x.key} key={x.key}>{x.name}</option>)}</select></label><label>Billing<select value={selection.data.billing_cycle} onChange={e=>selection.setData('billing_cycle',e.target.value)}><option value="monthly">Bulanan</option><option value="annual">Tahunan</option></select></label><button className="btn btn-secondary">Hitung ulang</button></form><form className="sv-register-card" onSubmit={checkout}><h2>Ringkasan pembayaran</h2>{subscription?<><div className="sv-total"><span>{subscription.plan?.name}</span><strong>{rupiah(subscription.base_amount)}</strong></div><div className="sv-total"><span>{subscription.business_configuration?.name}</span><strong>{rupiah(subscription.configuration_amount)}</strong></div><div className="sv-total grand"><span>Total</span><strong>{rupiah(subscription.total_amount)}</strong></div></>:<p>Belum ada subscription pending.</p>}<label>Metode<select value={pay.data.payment_method} onChange={e=>pay.setData('payment_method',e.target.value)}><option value="va">Virtual Account</option><option value="qris">QRIS</option></select></label><label>Channel<input value={pay.data.payment_channel} onChange={e=>pay.setData('payment_channel',e.target.value)} placeholder="bca / mandiri / qris"/></label><button className="btn btn-primary" disabled={!subscription||pay.processing}>Bayar via iPaymu</button><small>Butuh bantuan? {support?.phone||'081293047587'}</small></form></div></PublicShell>;
}
